name: Build and Deploy to AWS

#on:
#  push:
#    branches:
#      - main

on:
  workflow_dispatch: # This allows you to run the workflow manually

# Add permissions for the workflow to get a token from GitHub's OIDC provider
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Shortening Service
        run: mvn -f shortening-service/pom.xml clean package

      - name: Build Redirect Service
        run: mvn -f redirect-service/pom.xml clean package

      - name: Build Analytics Service
        run: mvn -f analytics-service/pom.xml clean package
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # This step now uses the IAM Role
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve